### ISSUE TITLE
Add eventing command to run Knative Eventing scaling tests

### ISSUE THREAD

**Issue by aslom** [knative-extensions/kperf#24]
I am working on eventing scaling tests https://github.com/knative/eventing/issues/4462 and I think it would be great if I could add eventing to tests to kperf.

As far as I understand I will need to provide implementation of new kperf/pkg/command ?

What would be the best way to start? Write new user stories similiar to https://github.com/knative-sandbox/kperf#user-stories ?

I could show the tests I already have and then discuss how they could be integrated wit kperf user experience?

Where would be the best place to discuss it?

**Comment by zhanggbj** [comment]
Hi @aslom 

I think It's great if kperf can support eventing and folks also brought this up before. It's nice that you have detailed eventing test cases and experience.

For now, kperf works in this way 1) generate Serving resources workload 2) collect resources metrics like time duration 3) visualize metics. Some parts are general and we could leverage them for Eventing support.

I think a specific Google proposal would be great with background/user stories/design/etc, and then we can discuss together about how to move forward with the doc or in the community WG meeting. Here is the [kerf proposal](https://docs.google.com/document/d/1Q7U2wzRiCA6BApsLyooXrN1FuwUlPy8AXpJXj4JtKIg/edit?usp=sharing). FYI.

cc @maximilien @duglin @julz @mattmoor @chizhg for more insights. Thanks!

**Comment by aslom** [comment]
@zhanggbj I will prepare google doc proposal for eventing testing in kperf that is similiar the google doc you provided.

**Comment by maximilien** [comment]
Great idea @aslom. Thanks for this. Best.

**Comment by aslom** [comment]
@maximilien @zhanggbj I have drafted proposal to add eventing functionality to kperf: 

https://docs.google.com/document/d/1BHQ9bvo7Sir1NrUrz1-iXKNn2bRPclf-Xf0vFf4HV64/edit?usp=sharing&resourcekey=0-_xDvW1SMNzSyuB019Mr-Zg

Please let me know if you see anything missing there. The proposal is based on python and go code that I have developed and I worked to make it fit into kperf design with prepare and measure commands. 

I have also talked with @lionelvillard @zroubalik @aavarghese to gather requirements for Knative eventing testing for sources and for autoscaling with KEDA and included that in the proposal.

**Comment by zroubalik** [comment]
Thanks for the proposal @aslom, these is very useful. 
+1 from me

**Comment by aslom** [comment]
Here is current plan for initial code based on the proposal:
* prepare: deploys Receiver for events in one namespace - Receiver can handle receiving events over HTTP and provide metrics for HTTP (to be retrieved by kperf CLI)
* measure: launches Test Driver job in one namespace that generates events workload that is then monitored by kperf CLI to continuously retrieve metrics from Receiver and convert them into text output and .csv file (maybe JSON as well)
* cleanup: deletes Receiver and Test Driver jobs from namespace

Comments?

**Comment by zhanggbj** [comment]
@aslom

Thanks for the nice proposal for eventing support!
As discussed offline, I will take a look this week and get back to you later.

**Comment by aslom** [comment]
I have added example of `kperf eventing` could be used:
* Setup Knative including Knative Eventing (sources, channels, brokers)
* Run `kperf eventing prepare -n 1 ` to deploy vents receiver in namespace test-1
* Configure Knative Eventing setup to use test eventing receiver as sink (the same way as event-display is configured as documented in Knative docs)
* Run `kperf eventing measure -n 1 -c 10 -e 100 -p 5s -i 50 -d 30s`  to run test driver in test-1 namespace with concurrency 10 sending initially 100 events/second (sending total 10*100=1000 events/second in total) for 5 seconds and then increasing the number of events to send by 50 (to 150 events/second) and continue increasing for 30 seconds. Every second the output is printed with metrics retrieved from the receiver (see User Story 2 for more details).
* Do other measurement step for other setups by doing two previous steps

Then for clanup:
* Configure Knative Eventing to no longer use receiver as sink
* Run kperf eventing cleanup -n 1 to undeploy receiver and remove test drivers

**Comment by aslom** [comment]
I updated MVP plan to break into smaller stages and PRS:
https://docs.google.com/document/d/1BHQ9bvo7Sir1NrUrz1-iXKNn2bRPclf-Xf0vFf4HV64/edit?resourcekey=0-_xDvW1SMNzSyuB019Mr-Zg#heading=h.ndfzzi8khupd

I am going now to open issues and start working on PR for first one.

**Comment by maximilien** [comment]
Yeah, thanks @aslom
