### ISSUE TITLE
As a Kperf developer, I want to support a flag to specify result location 

### ISSUE THREAD

**Issue by zhanggbj** [knative-extensions/kperf#48]
For now, by default we save results under `/tmp`.

There is a comment requirement to specify the result location instead of default `/tmp`.

We would like to support `--output` flag to specify the result location.

Also we want to support https://docs.google.com/document/d/1p8Y4CEgAUC4KvVgrSQ5tOH6MZo27nlw-eTQ3tR6Gi2c/edit#

"kperf needs to support a --output-destination flag to control whether the results should be written to Mako or local .csv files."

/CC @chizhg @maximilien 

- [x] --output flag with custom directory
- [ ] --output mako support

**Comment by ShiningTian** [comment]
I will work on this.

**Comment by zhanggbj** [comment]
@chizhg 
#59 is to add `--output` flag, would you please help to take a review, if it can meet the request?

BTW, about `write to Mako`, it is just a file directory, or it is some service address like S3?

**Comment by chizhg** [comment]
@zhanggbj 
Thanks for taking this work! I'll review the PR.

Regarding `write to Mako`, it's probably a bit more complicated than you expected. https://github.com/google/mako/blob/master/docs/GUIDE.md#using-the-mako-quickstore-client is the document for using the Mako client library to write the data to `Quickstore`. Also please note you need to start the Mako microservice before it, which is usually run as a sidecar container in a Pod.

Below are example links for benchmarks in serving:
https://github.com/knative/serving/blob/main/test/performance/benchmarks/dataplane-probe/continuous/main.go#L114
https://github.com/knative/serving/blob/main/test/performance/benchmarks/dataplane-probe/continuous/dataplane-probe.yaml#L56-L67

**Comment by zhanggbj** [comment]
@chizhg 

Cool, thanks for the precise info. We'll take a look and get back to you later.
