### ISSUE TITLE
As a Kperf developer, I want to support SLO expectation for each metric

### ISSUE THREAD

**Issue by zhanggbj** [knative-extensions/kperf#49]
This requirement came from https://docs.google.com/document/d/1p8Y4CEgAUC4KvVgrSQ5tOH6MZo27nlw-eTQ3tR6Gi2c/edit#.

I think this is common, not just for Mako integration. I think kperf can add support for SLO.

Refer to https://sre.google/workbook/implementing-slos/ for more explanation for SLO.

**Comment by gyohuangxin** [comment]
@chizhg Hi, it says that the SLO can be used by Mako, but is there an example of how Mako use SLO now?  Thanks!

**Comment by chizhg** [comment]
Mako provides a few implementations of https://github.com/google/mako/blob/master/docs/ANALYZERS.md that can be used to determine if the aggregated metrics meet the given SLOs.

One example used in serving benchmarks can be found at https://github.com/knative/serving/blob/main/test/performance/benchmarks/load-test/continuous/main.go#L134-L137

**Comment by gyohuangxin** [comment]
@chizhg Thanks so much, that's very helpful. My understanding is that we need add SLO support to determine whether the benchmark passed or failed. So we just need return like "pass" or "fail" after run `kperf ... --slo=latency-p99<1,thoughput-mean>1000`. Is it a correct understanding?

**Comment by chizhg** [comment]
@gyohuangxin Yes, your understanding is correct.

We also implemented a library that can send alert to Slack and open an issue on GitHub if performance regressions are detected, and it's in https://github.com/knative/pkg/blob/main/test/mako/alerter/alerter.go#L55. Examples are https://knative.slack.com/archives/C94SPR60H/p1611935859045100 and https://github.com/knative/serving/issues/10650. So this can also be integrated with kperf.

**Comment by gyohuangxin** [comment]
@chizhg Thanks for your information!
